<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    xmi:id="_JTE78MQwEeuyUouQYKpTOg"
    name="carrito">
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKf8QwEeuyUouQYKpTOg"
      name="Articulo">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKgMQwEeuyUouQYKpTOg"
        name="int precio">
      <eAnnotations
          xmi:id="_JTGKgMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKgMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKgMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKgcQwEeuyUouQYKpTOg"
        name="String nombre">
      <eAnnotations
          xmi:id="_JTGKgcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKgcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKgcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKgsQwEeuyUouQYKpTOg"
        name="String codigo">
      <eAnnotations
          xmi:id="_JTGKgsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKgsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKgsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKg8QwEeuyUouQYKpTOg"
        name="int talla">
      <eAnnotations
          xmi:id="_JTGKg8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKg8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKg8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKhMQwEeuyUouQYKpTOg"
        name="String marca">
      <eAnnotations
          xmi:id="_JTGKhMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKhMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKhMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKhcQwEeuyUouQYKpTOg"
        name="zapatos"
        eType="_JTGKicQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKhcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKhcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKhcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKhsQwEeuyUouQYKpTOg"
        name="poleras"
        eType="_JTGKi8QwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKhsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKhsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKhsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKh8QwEeuyUouQYKpTOg"
        name="pantalones"
        eType="_JTGKjcQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKh8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKh8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKh8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKiMQwEeuyUouQYKpTOg"
        name="ordendedespacho"
        eType="_JTGKnMQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKiMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKiMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKiMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKicQwEeuyUouQYKpTOg"
      name="Zapato">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKisQwEeuyUouQYKpTOg"
        name="modelo">
      <eAnnotations
          xmi:id="_JTGKisQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKisQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKisQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKi8QwEeuyUouQYKpTOg"
      name="Poleron">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKjMQwEeuyUouQYKpTOg"
        name="color">
      <eAnnotations
          xmi:id="_JTGKjMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKjMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKjMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKjcQwEeuyUouQYKpTOg"
      name="Pantalon">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKjsQwEeuyUouQYKpTOg"
        name="color">
      <eAnnotations
          xmi:id="_JTGKjsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKjsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKjsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKj8QwEeuyUouQYKpTOg"
        name="bolsillos">
      <eAnnotations
          xmi:id="_JTGKj8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKj8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKj8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKkMQwEeuyUouQYKpTOg"
      name="Pago Interface">
    <eOperations
        xmi:id="_JTGKkcQwEeuyUouQYKpTOg"
        name="pago">
      <eAnnotations
          xmi:id="_JTGKkcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKkcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKkcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eOperations
        xmi:id="_JTGKksQwEeuyUouQYKpTOg"
        name="ordenes">
      <eAnnotations
          xmi:id="_JTGKksQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKksQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKksQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKk8QwEeuyUouQYKpTOg"
        name="ordendedespacho"
        eType="_JTGKnMQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKk8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKk8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKk8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKlMQwEeuyUouQYKpTOg"
      name="Credito">
    <eOperations
        xmi:id="_JTGKlcQwEeuyUouQYKpTOg"
        name="pago credito">
      <eAnnotations
          xmi:id="_JTGKlcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKlcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKlcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKlsQwEeuyUouQYKpTOg"
        name="cuotasmax">
      <eAnnotations
          xmi:id="_JTGKlsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKlsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKlsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKl8QwEeuyUouQYKpTOg"
        name="pago interface"
        eType="_JTGKkMQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKl8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKl8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKl8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKmMQwEeuyUouQYKpTOg"
      name="Debito">
    <eOperations
        xmi:id="_JTGKmcQwEeuyUouQYKpTOg"
        name="pago debito">
      <eAnnotations
          xmi:id="_JTGKmcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKmcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKmcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKmsQwEeuyUouQYKpTOg"
        name="total">
      <eAnnotations
          xmi:id="_JTGKmsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKmsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKmsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKm8QwEeuyUouQYKpTOg"
        name="pago interface"
        eType="_JTGKkMQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKm8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKm8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKm8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKnMQwEeuyUouQYKpTOg"
      name="ordenDeDespacho">
    <eOperations
        xmi:id="_JTGKncQwEeuyUouQYKpTOg"
        name="agregararticulo">
      <eAnnotations
          xmi:id="_JTGKncQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKncQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKncQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eOperations
        xmi:id="_JTGKnsQwEeuyUouQYKpTOg"
        name="carrito">
      <eAnnotations
          xmi:id="_JTGKnsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKnsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKnsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eOperations
        xmi:id="_JTGKn8QwEeuyUouQYKpTOg"
        name="ordendespacho">
      <eAnnotations
          xmi:id="_JTGKn8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKn8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKn8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eOperations
        xmi:id="_JTGKoMQwEeuyUouQYKpTOg"
        name="mostrarmenu">
      <eAnnotations
          xmi:id="_JTGKoMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKoMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKoMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eOperations
        xmi:id="_JTGKocQwEeuyUouQYKpTOg"
        name="venta">
      <eAnnotations
          xmi:id="_JTGKocQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKocQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKocQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKosQwEeuyUouQYKpTOg"
        name="Cliente cliente">
      <eAnnotations
          xmi:id="_JTGKosQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKosQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKosQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKo8QwEeuyUouQYKpTOg"
        name="listadeProductos">
      <eAnnotations
          xmi:id="_JTGKo8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKo8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKo8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKpMQwEeuyUouQYKpTOg"
        name="codigosproducto">
      <eAnnotations
          xmi:id="_JTGKpMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKpMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKpMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKpcQwEeuyUouQYKpTOg"
        name="montototal">
      <eAnnotations
          xmi:id="_JTGKpcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKpcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKpcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKpsQwEeuyUouQYKpTOg"
        name="fechacompra">
      <eAnnotations
          xmi:id="_JTGKpsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKpsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKpsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      xmi:id="_JTGKp8QwEeuyUouQYKpTOg"
      name="Cliente">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKqMQwEeuyUouQYKpTOg"
        name="String direccion">
      <eAnnotations
          xmi:id="_JTGKqMQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKqMQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKqMQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKqcQwEeuyUouQYKpTOg"
        name="nombre cliente">
      <eAnnotations
          xmi:id="_JTGKqcQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKqcQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKqcQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        xmi:id="_JTGKqsQwEeuyUouQYKpTOg"
        name="rut">
      <eAnnotations
          xmi:id="_JTGKqsQwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKqsQwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKqsQwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        xmi:id="_JTGKq8QwEeuyUouQYKpTOg"
        name="ordendedespacho"
        eType="_JTGKnMQwEeuyUouQYKpTOg">
      <eAnnotations
          xmi:id="_JTGKq8QwEeuyUouQYKpTOg0"
          source="genmymodel">
        <details
            xmi:id="_JTGKq8QwEeuyUouQYKpTOg00"
            key="uuid"
            value="_JTGKq8QwEeuyUouQYKpTOg"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
