<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="andromdacommon"
    nsURI="http:///andromdacommon.ecore"
    nsPrefix="andromdacommon">
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="TernaryBoolean">
    <eLiterals
        name="default"
        literal="default"/>
    <eLiterals
        name="true"
        value="1"
        literal="true"/>
    <eLiterals
        name="false"
        value="2"
        literal="false"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Mapped">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Role">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaRoleName"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseActor"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Exception">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaSerialVersionUid"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SimpleClass">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaSerialVersionUid"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MapsWith">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseDependency"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Future">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseElement"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ExceptionRef">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseDependency"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DocOnly">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseElement"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UnexpectedException"
      eSuperTypes="//Exception"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ApplicationException"
      eSuperTypes="//Exception"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Enumeration">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaSerialVersionUid"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EnvEntry">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseProperty"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Keywords">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="override"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="synchronized"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="transient"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="volatile"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="deprecated"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="none"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseOperation"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseProperty"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Nullable">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseParameter"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SuppressWarnings">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="unchecked"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="fallthrough"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="javadoc"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="serial"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="finally"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="all"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="unused"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="emptyBlock"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="null"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseElement"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ValueObject">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaXmlBindingAnnotations"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="default"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaGenerateEqualPropertiesMethod"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="default"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaXmlAttributes"
        ordered="false"
        lowerBound="1"
        defaultValueLiteral="default"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaSerialVersionUid"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Singleton">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Ignore">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseElement"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Facade">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Factory">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MapsTo">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="domainAttributeName"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="domainClassName"
        ordered="false"
        lowerBound="1">
      <eAnnotations
          source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details
            key="originalName"
            value="domain_class_name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseProperty"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Serializable">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaSerialVersionUid"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseInterface"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseClass"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Validation">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationBaseType"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationFixed"
        ordered="false"
        defaultValueLiteral="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationLength"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationMinLength"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationMaxLength"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationPattern"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationWhiteSpace"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationMaxInclusive"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationMaxExclusive"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationMinExclusive"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationMinInclusive"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationTotalDigits"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="andromdaValidationFractionDigits"
        ordered="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseProperty"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseParameter"
        ordered="false"
        lowerBound="1"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseDataType"
        ordered="false"
        lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
